Revert "Update dependency react-dropzone to v14.3.5 (develop)"
This reverts commit eef9e57aa7ce81ed0e13997baa631591551e64c6.

After the update, the upload failes with the following message:

Error: Illegal input

The values could not be validated. Please correct your input and try again.

Violations:

./my.file: Path